<script lang="ts">
  import type { PageData } from '../$types';
  import MarkdownRenderer from '$lib/components/research/MarkdownRenderer.svelte';

  let { data }: { data: PageData } = $props();

  const report   = $derived(data.report);
  const rating   = $derived(report.rating);
  const overview = $derived(report.overview);

  const confidenceLabel = $derived(
    rating.moatScore >= 8.5 ? 'High' :
    rating.moatScore >= 7.0 ? 'Medium-High' :
    'Medium'
  );

  const confidenceColor = $derived(
    rating.moatScore >= 8.5 ? 'text-[var(--green)]' :
    rating.moatScore >= 7.0 ? 'text-[var(--amber)]' :
    'text-[var(--text-muted)]'
  );

  // Extract key insights from the analysis (first 4 paragraphs after headers as bullets)
  const keyInsights = $derived([
    `Signal: ${rating.signal.replace('-', ' ').toUpperCase()} — Target ${overview.market === 'CN' ? '¥' : overview.market === 'HK' ? 'HK$' : '$'}${rating.targetPrice.toLocaleString()} (+${rating.safetyMargin.toFixed(1)}% upside)`,
    `Moat Score: ${rating.moatScore.toFixed(1)}/10 — ${rating.moatScore >= 8 ? 'Wide' : rating.moatScore >= 6 ? 'Narrow' : 'No'} Moat classification`,
    `Risk Level: ${rating.riskLevel.charAt(0).toUpperCase() + rating.riskLevel.slice(1)} — ${report.risks.filter(r => r.severity === 'high').length} high-severity risk factors identified`,
    `${report.catalysts.filter(c => c.impact === 'positive').length} positive catalysts identified in the next 12 months`
  ]);

  function formatDate(dateStr: string): string {
    const d = new Date(dateStr);
    return d.toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });
  }
</script>

<div class="space-y-5">
  <h2 class="text-[11px] font-mono uppercase tracking-wider text-[var(--text-muted)]">Meridian AI Analysis</h2>

  <!-- AI Verdict Hero -->
  <div class="bg-[var(--bg-surface)] border border-[var(--border-default)] rounded-xl p-5">
    <div class="flex items-start gap-4">
      <!-- AI icon -->
      <div class="w-10 h-10 rounded-xl bg-[var(--bg-elevated)] border border-[var(--border-default)] flex items-center justify-center shrink-0" aria-hidden="true">
        <svg class="w-5 h-5 text-[var(--text-secondary)]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"
            d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"
          />
        </svg>
      </div>
      <div class="flex-1">
        <div class="flex items-center gap-2 flex-wrap mb-1">
          <h3 class="text-base font-semibold text-[var(--text-primary)]">AI Analysis</h3>
          <span class="px-2 py-0.5 rounded text-xs font-mono bg-[var(--bg-elevated)] border border-[var(--border-default)] text-[var(--text-muted)]">
            {overview.ticker} · {overview.name}
          </span>
        </div>
        <div class="flex items-center gap-3 text-xs text-[var(--text-muted)]">
          <span class="font-mono">Generated {formatDate(report.generatedAt)}</span>
          <span class="text-[var(--text-dimmed)]">·</span>
          <span>Confidence: <span class="font-medium {confidenceColor}">{confidenceLabel}</span></span>
        </div>
      </div>
    </div>
  </div>

  <!-- Key Insights -->
  <div class="bg-[var(--bg-surface)] border border-[var(--border-default)] rounded-xl p-5">
    <h3 class="text-[11px] font-mono uppercase tracking-wider text-[var(--text-muted)] mb-3">Key Takeaways</h3>
    <div class="grid grid-cols-1 sm:grid-cols-2 gap-2">
      {#each keyInsights as insight, i}
        <div class="flex items-start gap-2 p-3 bg-[var(--bg-elevated)] rounded-lg border border-[var(--border-default)]">
          <span class="text-xs font-mono text-[var(--text-dimmed)] shrink-0 mt-0.5">{String(i + 1).padStart(2, '0')}</span>
          <p class="text-xs text-[var(--text-secondary)] leading-relaxed">{insight}</p>
        </div>
      {/each}
    </div>
  </div>

  <!-- Full Analysis -->
  <div class="bg-[var(--bg-surface)] border border-[var(--border-default)] rounded-xl p-6">
    <MarkdownRenderer content={report.novaAnalysis} />
  </div>

  <!-- Disclaimer -->
  <div class="bg-[var(--bg-elevated)] border border-[var(--border-default)] rounded-xl p-4">
    <p class="text-[11px] font-mono uppercase tracking-wider text-[var(--text-dimmed)] mb-1.5">Disclaimer</p>
    <p class="text-xs text-[var(--text-dimmed)] leading-relaxed">
      This analysis is generated by Meridian AI for research and educational purposes only. It does not constitute financial advice, investment advice, trading advice, or any other sort of advice. Past performance is not indicative of future results. All investments involve risk, including the possible loss of principal. Always conduct your own due diligence before making investment decisions.
    </p>
  </div>
</div>
